app_name: Another Hydra Site
theme: default
domain: hydra.org
domain_base: hydra
domain_with_port: hydra.org:3001
tagline: Yet another Hydra Tracker
items_per_page: 10
webmaster_email: hydratracker@gmail.com
webmaster_name: Webmaster
notifiction_email: noreply@mongoose.com
