# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "categories", :force => true do |t|
    t.column "name", :string
  end

  create_table "peers", :force => true do |t|
    t.column "torrent_id",      :integer
    t.column "peer_id",         :string
    t.column "ip",              :string
    t.column "port",            :integer
    t.column "passkey",         :string
    t.column "uploaded",        :integer,  :default => 0
    t.column "downloaded",      :integer,  :default => 0
    t.column "to_go",           :integer,  :default => 0
    t.column "seeder",          :boolean,  :default => false
    t.column "connectable",     :boolean,  :default => false
    t.column "user_id",         :integer
    t.column "agent",           :string
    t.column "finished_at",     :datetime
    t.column "download_offset", :integer,  :default => 0
    t.column "upload_offset",   :integer,  :default => 0
    t.column "last_action_at",  :datetime
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  add_index "peers", ["torrent_id", "peer_id"], :name => "index_peers_on_torrent_id_and_peer_id", :unique => true
  add_index "peers", ["connectable"], :name => "index_peers_on_connectable"

  create_table "torrent_files", :force => true do |t|
    t.column "torrent_id", :integer
    t.column "filename",   :text
    t.column "size",       :integer
  end

  create_table "torrents", :force => true do |t|
    t.column "info_hash",          :string
    t.column "name",               :string
    t.column "user_id",            :integer
    t.column "filename",           :string
    t.column "original_filename",  :string
    t.column "description",        :text
    t.column "category_id",        :integer
    t.column "size",               :integer
    t.column "piece_length",       :integer
    t.column "pieces",             :integer
    t.column "orig_announce_url",  :string
    t.column "orig_announce_list", :text
    t.column "created_by",         :string
    t.column "torrent_comment",    :string
    t.column "numfiles",           :integer
    t.column "views",              :integer,  :default => 0
    t.column "times_completed",    :integer,  :default => 0
    t.column "leechers",           :integer,  :default => 0
    t.column "seeders",            :integer,  :default => 0
    t.column "created_at",         :datetime
    t.column "updated_at",         :datetime
  end

  add_index "torrents", ["info_hash"], :name => "index_torrents_on_info_hash"

  create_table "users", :force => true do |t|
    t.column "login",                  :string
    t.column "hashed_password",        :string
    t.column "salt",                   :string
    t.column "is_admin",               :boolean,  :default => false
    t.column "is_editor",              :boolean,  :default => false
    t.column "remember_token",         :string
    t.column "remember_token_expires", :datetime
    t.column "created_at",             :datetime
    t.column "updated_at",             :datetime
  end

end
